# Generated by Django 5.2.15 on 2026-07-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='jds/', verbose_name='Job Description'),
        ),
    ]
