# Generated by Django 5.2.16 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_jd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.PositiveIntegerField(default=1, help_text='Number of positions to fill.'),
        ),
    ]
