# Generated by Django 5.2.16 on 2026-07-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
