# Generated by Django 5.2.15 on 2026-07-06 10:53

import candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Education')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Institution')),
                ('last_role', models.CharField(blank=True, max_length=255, null=True)),
                ('last_company', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SHORTLISTED', 'Shortlisted'), ('ROUND1', 'Round 1'), ('INTERVIEW', 'Interview'), ('FINAL_SELECTION', 'Final Selection'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('BLACKLISTED', 'Blacklisted')], default='OPEN', max_length=30)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_blob_url', models.FileField(blank=True, null=True, upload_to=candidates.models.candidate_resume_path, verbose_name='Resume')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('blacklisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('year_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-year_completed'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_set', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='candidates.candidate')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidate status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application_count', models.PositiveIntegerField(default=1)),
                ('last_applied_at', models.DateTimeField(auto_now=True)),
                ('first_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.candidate')),
            ],
        ),
    ]
