# Generated by Django 5.2.16 on 2026-07-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_attachment_communicationlog_note_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, help_text='External link to the resume (e.g. SharePoint/Drive).', max_length=1000, null=True, verbose_name='Resume Link'),
        ),
    ]
