# Generated by Django 5.2.16 on 2026-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='performed_by',
            field=models.CharField(blank=True, help_text='Who actually performed this action (free text).', max_length=150, null=True, verbose_name='Done by'),
        ),
    ]
