# Generated by Django 5.2.16 on 2026-07-10 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatestatushistory_performed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
