# Generated by Django 5.2.16 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidatestatushistory_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('SHORTLISTED', 'Shortlisted after call'), ('UNABLE', 'Unable to connect'), ('CALLBACK', 'Call back'), ('NOT_SHORTLISTED', 'Not shortlisted')], max_length=20, null=True),
        ),
    ]
