# Generated by Django 5.2.16 on 2026-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_is_on_hold_communicationlog_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_summary',
            field=models.TextField(blank=True, help_text='Short AI-generated summary of the resume.', null=True, verbose_name='AI CV Summary'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('INTERVIEW', 'Interview'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('UNABLE', 'Unable to connect'), ('CALLBACK', 'Call back'), ('NOT_TURNED_UP', 'Not turned up'), ('ATTENDED', 'Attended'), ('SHORTLISTED', 'Shortlisted after call'), ('NOT_SHORTLISTED', 'Not shortlisted')], max_length=20, null=True),
        ),
    ]
