# Generated by Django 5.2.16 on 2026-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_cv_summary_alter_communicationlog_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SHORTLISTED', 'Shortlisted'), ('ROUND1', 'Round 1'), ('INTERVIEW', 'Interview'), ('FINAL_SELECTION', 'Final Selection'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('BLACKLISTED', 'Blacklisted'), ('SCREENING_HOLD', 'Screening Hold')], default='OPEN', max_length=30),
        ),
    ]
